# Generated by Django 3.2.8 on 2021-11-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='jawaban',
        ),
        migrations.AddField(
            model_name='faq',
            name='nama',
            field=models.CharField(default='asd', max_length=30),
            preserve_default=False,
        ),
    ]
